services:
  backend:
    build:
      context: servidor_docker_backend/
      dockerfile: Dockerfile
    environment:
      DATABASE_PORT: 5000
      SERVER_PORT: 5001
      MQTT_SERVER: cjsg.ddns.net
      MQTT_PORT: 1883
      MQTT_USERNAME: cd
      MQTT_PASSWORD: 1qaz"WSX
      MQTT_TOPIC: /weather
    ports:
      - "5001:5001"
    depends_on:
      - database
  database:
    build:
      context: servidor_docker_db/
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 5000
    ports:
      - "5000:5000"
